console.log("Welcome Anuj singh");
console.log("welcome");
console.log("welcome");
console.log("welcome");
console.log("welcome");
console.log("welcome");
console.log("welcome");
console.log("welcome");
console.log("welcome");
console.log("welcome");
console.log("welcome");
